baseurl = "/"
title = "颜林林的个人网站"
theme = "simple-style"
paginate = 20
googleAnalytics = "UA-74397492-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "2007-2019 Linlin Yan. [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/deed.zh)"

[markup.goldmark.renderer]
unsafe = true

[params]
subtitle = "Linlin Yan's Personal Website"
favicon = "/logo/logo.ico"

[markup.highlight]
codeFences = true
lineNos = true
style = "monokailight"

[permalinks]
post = "/:year/:month/:slug/"
page = "/:slug/"

[taxonomies]
tag = "tags"

[[menu.main]]
weight = 10
name = "博客"
url = "/"

[[menu.main]]
weight = 20
name = "公众号"
url = "/public/"

[[menu.main]]
weight = 30
name = "朋友圈"
url = "/moments/"

[[menu.main]]
weight = 40
name = "作品"
url = "/works/"

[[menu.main]]
weight = 90
name = "关于"
url = "/about/"
