baseurl = "/"
title = "颜林林的个人网站"
theme = "simple-style"
paginate = 20
googleAnalytics = "UA-74397492-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
copyright = "2007-2019 Linlin Yan"

[params]
subtitle = "Linlin Yan's Personal Website"
favicon = "/logo/logo.ico"

[markup.highlight]
codeFences = true
lineNos = true
style = "monokailight"

[permalinks]
post = "/:year/:month/:slug/"
page = "/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
weight = 10
name = "博客"
url = "/"

[[menu.main]]
weight = 90
name = "关于"
url = "/about/"
